version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: user-crud-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/user_crud_db
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: user-crud-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
